### ISSUE TITLE
Add Data Protection Declaration Content-Type

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-cms#137]
- Single Type

**Comment by mahtabiltarabian** [comment]
<img width="457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1lHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e2e908c0e15f11f59d0eb9d886f300020addb4d/image.png" alt="image.png" />
