### ISSUE TITLE
Create new Prevalence data model

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-cms#147]
Jahr
Mikroorganismus
Oberkategorie Probenursprung (Tier/Lebensmiitel/Futtermittel)
Probenursprung (Tier/Lebensmiitel/Futtermittel)
Probenahmestelle
Matrixgruppe
Matrix

**Comment by tasjacrease** [comment]
There is a typing error in my data model. It should be Lebensmittel and not Lebensmiitel.

**Comment by tasjacrease** [comment]
We should have the possibilty to filter for all the attributes listed above. Even though not all of them appear in the data table. Should I create a new ticket for this?
