### ISSUE TITLE
Add output file to prevalence import

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-cms#152]
Seeresistance data output file

**Comment by mahtabiltarabian** [comment]
<img width="521" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUd5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--beb626c642714296520ff54e8698e80feecd1ae5/image.png" alt="image.png" />
