### ISSUE TITLE
Remove superfluous Microorganisms from db

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-cms#181]
As a user I find it confusing that we have microorganims in the drop down list of the filter on the prevalence page without data for those microorganisms.On the prevalence page we do not have data for E. coli and Enterococcus in the data base. Can we delete these microorganisms from the drop down

**Comment by mahtabiltarabian** [comment]
@Dominic 
I removed E. coli and Enterococcus in dev. please remove this in
