### ISSUE TITLE
As an API-User I want to be able to consume the zono isolate data in linked data format 

### ISSUE THREAD

**Issue by ckchinmay** [SiLeBAT/zoonotify-cms#4]
Workflow-
1. User will pass a simple search criteria say "pig" to the API
2. API will return the JSON linked data as a response.

Process-
1. API will find the records matching to the passed criteria
2. API will then translate the response into the JSON LD format using the master data
3. fields/data which does not have master data mapping will be shown as is for now.
 
Assumptions:
1. Existing Linked Data created by Mariel will be treated to the tables inside database and used as master data
2. Admin will be responsible to add/modify of the said master data

**Comment by dptolle** [comment]
@ckchinmay This can be closed once the CT renaming and import script adjustments are complete, right?

**Comment by ckchinmay** [comment]
yes. It can be closed after current work.
